-- Migration 20250909010959_create_profiles_table.sql
-- -----------------------------------------------
-- Deprecated
-- This migration originally created the `public.profiles` table.
-- It has been superseded by 20250910063129_create_user_profiles_and_roles.sql,
-- which defines the full schema for `profiles` with role-based access control.
--
-- The original contents have been removed to prevent duplicate table creation.
-- Keeping this file as a no-op ensures migration history remains consistent.
