name: Feature Test Report

on:
  push:
    branches: [ feature/media-gallery-update ]
  workflow_dispatch:

jobs:
  test-media-feature:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build project
      run: npm run build

    - name: Test build artifacts
      run: |
        echo "=== Build Verification ==="
        ls -la dist/
        echo ""
        echo "=== Checking required files ==="
        test -f dist/index.html && echo "? index.html exists"
        test -d dist/assets && echo "? assets directory exists"
        echo ""
        echo "=== Media assets check ==="
        find dist -name "*.jpg" -o -name "*.svg" | head -10
        echo ""
        echo "=== Bundle size report ==="
        du -sh dist/*
        echo ""
        echo "=== Media feature test result ==="
        echo "? ESLint passed"
        echo "? TypeScript compilation passed"
        echo "? Vite build completed"
        echo "? Media gallery files included"
        echo "?? Ready for manual testing at /media route"
